apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: aom-microservice-admin-api-gateway-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aom-microservice-admin-api-gateway
  minReplicas: 1
  maxReplicas: 1

  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: 256Mi