apiVersion: v1
kind: Service
metadata:
  name: aom-microservice-admin-api-gateway-svc
spec:
  selector:
    app: aom-microservice-admin-api-gateway
  type: ClusterIP
  ports:
    - name: http-aom-microservice-admin-api-gateway
      protocol: TCP
      port: 3000
      targetPort: 3000
    # only for development
#    - name: prism
#      protocol: TCP
#      port: 4010
#      targetPort: 4010
